import type { Category, EventItem } from "./types";

export const CATEGORIES: Category[] = [
  "Festival",
  "Progressive",
  "Melodic House",
  "Trance",
  "Nightlife",
];

const cover = (slug: string) => `/event-covers/${slug}.jpg`;

export const EVENTS: EventItem[] = [
  {
    id: "1",
    slug: "odeysse-simon-vuarambon",
    title: "Odeysse: Simon Vuarambon",
    tagline: "A 7-hour extended set from one of progressive's most hypnotic selectors.",
    category: "Progressive",
    city: "Colombo",
    area: "Port City",
    venue: "Port City Open Grounds",
    date: "2026-07-18T18:00:00",
    startTime: "18:00",
    endTime: "01:00",
    ageLimit: 18,
    organizer: { name: "Odeysse", verified: true },
    lineupLabel: "Lineup",
    lineup: [
      { name: "Simon Vuarambon", role: "Headliner · 7hr set" },
      { name: "Kryptone", role: "Warm-up" },
      { name: "Rockka", role: "Breakout" },
    ],
    description: [
      "Odeysse presents Simon Vuarambon for a rare 7-hour extended journey — the kind of long-form set that lets a room truly travel.",
      "Sunset over the water, an open-air floor, and a soundsystem tuned for the space. Kryptone opens and Rockka takes the breakout room.",
    ],
    tiers: [
      { id: "final", name: "Final Phase", price: 45, fee: 4, blurb: "Guaranteed entry all night.", available: 180, badge: "Popular" },
      { id: "gate", name: "At the Gate", price: 55, fee: 4, blurb: "Pay-on-arrival, subject to capacity.", available: 220 },
      { id: "vip", name: "VIP", price: 120, fee: 8, blurb: "Raised deck, fast lane and private bar.", perks: ["Fast-lane entry", "VIP deck & view", "Private bar"], available: 30, badge: "Limited" },
      { id: "vvip", name: "VVIP Table", price: 250, fee: 14, blurb: "Reserved table for up to 4, bottle service.", perks: ["Reserved table (up to 4)", "Bottle service", "Dedicated host"], available: 8, badge: "Final Release" },
    ],
    image: cover("odeysse-simon-vuarambon"),
    accent: "#2f7dff",
    attending: 1240,
    capacity: 1800,
    featured: true,
  },
  {
    id: "2",
    slug: "kyotto-open-to-close",
    title: "KYOTTO: Open to Close",
    tagline: "One artist, twelve hours — a first-of-its-kind open-to-close in South Asia.",
    category: "Melodic House",
    city: "Colombo",
    area: "Colombo 03",
    venue: "The Members Club",
    date: "2026-07-25T18:00:00",
    startTime: "18:00",
    endTime: "06:00",
    ageLimit: 21,
    organizer: { name: "The Members Only", verified: true },
    lineupLabel: "Lineup",
    lineup: [
      { name: "KYOTTO", role: "Open to close · 12hr" },
      { name: "Members Only Residents", role: "Resident" },
    ],
    description: [
      "The Members Only presents KYOTTO for a full open-to-close: twelve hours, one artist, no support — a first-of-its-kind experience in South Asia.",
      "An intimate, members-first room built for deep listening and long stretches of melodic house and techno. Capacity is intentionally limited.",
    ],
    tiers: [
      { id: "early", name: "Early Access", price: 60, fee: 5, blurb: "Doors from 6PM.", available: 90, badge: "Best Value" },
      { id: "std", name: "Standard", price: 80, fee: 5, blurb: "Entry from 8PM.", available: 140, badge: "Popular" },
      { id: "member", name: "Members Table", price: 320, fee: 16, blurb: "Reserved table for 4, all-night host and bottle.", perks: ["Reserved table (up to 4)", "Bottle service", "All-night host"], available: 6, badge: "Limited" },
    ],
    image: cover("kyotto-open-to-close"),
    accent: "#f97316",
    attending: 410,
    capacity: 600,
    featured: true,
  },
  {
    id: "3",
    slug: "sudbeat-showcase-colombo",
    title: "Sudbeat Showcase",
    tagline: "Hernán Cattáneo's Sudbeat lands in Colombo with a stacked all-star bill.",
    category: "Progressive",
    city: "Colombo",
    area: "Port City",
    venue: "Port City Arena",
    date: "2026-07-31T17:00:00",
    startTime: "17:00",
    endTime: "03:00",
    ageLimit: 18,
    organizer: { name: "Nuwa Foresta × Tokyo Entertainment", verified: true },
    lineupLabel: "Lineup",
    lineup: [
      { name: "Hernán Cattáneo", role: "Headliner" },
      { name: "Danny Howells", role: "Headliner" },
      { name: "Gai Barone", role: "Support" },
      { name: "Graziano Raffa", role: "Support" },
      { name: "Kasey Taylor", role: "Support" },
      { name: "Dimuth K", role: "Local" },
    ],
    description: [
      "The legendary Sudbeat label showcase touches down in Colombo for the first time — a marathon of progressive and melodic sound led by Hernán Cattáneo and Danny Howells.",
      "A world-class international bill alongside the best of the local scene, on a festival-grade open-air stage overlooking the harbour.",
    ],
    tiers: [
      { id: "final", name: "Final Phase", price: 65, fee: 5, blurb: "Guaranteed entry.", available: 520, badge: "Popular" },
      { id: "gate", name: "At the Gate", price: 80, fee: 5, blurb: "Pay-on-arrival.", available: 400 },
      { id: "vip", name: "VIP Entry", price: 160, fee: 10, blurb: "Elevated deck, premium bars, fast lane.", perks: ["Fast-lane entry", "Elevated viewing deck", "Premium bars"], available: 60, badge: "Limited" },
    ],
    image: cover("sudbeat-showcase"),
    accent: "#12a06a",
    attending: 2980,
    capacity: 4000,
    featured: true,
  },
  {
    id: "4",
    slug: "rebirth-of-dusty-world",
    title: "Rebirth of Dusty World",
    tagline: "The Dusty World saga returns — six headliners, back-to-back, all day.",
    category: "Festival",
    city: "Colombo",
    area: "Rajagiriya",
    venue: "Lotus Tower Grounds",
    date: "2026-08-08T11:00:00",
    startTime: "11:00",
    endTime: "01:00",
    ageLimit: 18,
    organizer: { name: "Tickets Ministry", verified: true },
    lineupLabel: "Lineup",
    lineup: [
      { name: "Enzo Vood b2b Vegaz", role: "Headliner" },
      { name: "Subandrio b2b Noiyse Project", role: "Headliner" },
      { name: "Ultra b2b A-Jay", role: "Headliner" },
      { name: "Ayanth", role: "Support" },
      { name: "Noise Generation", role: "Support" },
      { name: "Shyro", role: "Support" },
    ],
    description: [
      "The Dusty World returns, reborn. Three back-to-back headline pairings power a fourteen-hour marathon under the Lotus Tower, from midday sun to the small hours.",
      "Free entry for April 11 ticket holders. Everyone else — grab a pre-sale before they're dusted.",
    ],
    tiers: [
      { id: "presale", name: "Pre-Sale", price: 40, fee: 4, blurb: "Lowest price, limited.", available: 300, badge: "Best Value" },
      { id: "final", name: "Final Phase", price: 55, fee: 4, blurb: "Guaranteed entry.", available: 620, badge: "Popular" },
      { id: "gate", name: "At the Gate", price: 70, fee: 4, blurb: "Pay-on-arrival.", available: 500 },
      { id: "vip", name: "VIP", price: 140, fee: 9, blurb: "Fast lane, VIP deck, dedicated bar.", perks: ["Fast-lane entry", "VIP deck", "Dedicated bar"], available: 50, badge: "Limited" },
    ],
    image: cover("rebirth-of-dusty-world"),
    accent: "#eab308",
    attending: 5200,
    capacity: 7000,
    featured: true,
  },
  {
    id: "5",
    slug: "flying-dust-festival",
    title: "Flying Dust Festival",
    tagline: "The flagship Dusty World festival — bigger stage, deeper bass, longer night.",
    category: "Festival",
    city: "Colombo",
    area: "Port City",
    venue: "Port City Open Grounds",
    date: "2026-08-22T16:00:00",
    startTime: "16:00",
    endTime: "02:00",
    ageLimit: 18,
    organizer: { name: "Tickets Ministry", verified: true },
    lineupLabel: "Lineup",
    lineup: [
      { name: "Enzo Vood", role: "Headliner" },
      { name: "Vegaz", role: "Headliner" },
      { name: "Ultra", role: "Support" },
      { name: "A-Jay", role: "Support" },
      { name: "Kryptone", role: "Local" },
    ],
    description: [
      "The flagship Flying Dust Festival returns to Port City with a full production build — a towering stage, a deeper soundsystem, and the crew that started it all.",
      "Early Raver tickets are the move. Gates at 4PM, headliners after dark.",
    ],
    tiers: [
      { id: "early", name: "Early Raver", price: 35, fee: 4, blurb: "First release, cheapest entry.", available: 0, soldOut: true },
      { id: "final", name: "Final Phase", price: 50, fee: 4, blurb: "Guaranteed entry.", available: 480, badge: "Popular" },
      { id: "gate", name: "At the Gate", price: 65, fee: 4, blurb: "Pay-on-arrival.", available: 420 },
      { id: "vip", name: "VIP", price: 130, fee: 9, blurb: "Fast lane, raised deck, private bar.", perks: ["Fast-lane entry", "Raised deck", "Private bar"], available: 44, badge: "Limited" },
    ],
    image: cover("flying-dust-festival"),
    accent: "#f5b000",
    attending: 3400,
    capacity: 5000,
  },
  {
    id: "6",
    slug: "kamilo-sanclemente",
    title: "Kamilo Sanclemente Live",
    tagline: "The Colombian progressive maestro returns to the Dusty World.",
    category: "Progressive",
    city: "Colombo",
    area: "Cinnamon Gardens",
    venue: "Arcade Independence Square",
    date: "2026-09-05T18:00:00",
    startTime: "18:00",
    endTime: "00:00",
    ageLimit: 18,
    organizer: { name: "Biauralis", verified: true },
    lineupLabel: "Lineup",
    lineup: [
      { name: "Kamilo Sanclemente", role: "Headliner" },
      { name: "Dimuth K", role: "Support" },
      { name: "Ranidu", role: "Support" },
    ],
    description: [
      "Colombia's Kamilo Sanclemente returns to the Dusty World with a headline set of the deep, emotive progressive house he's known for worldwide.",
      "An open-air courtyard show under the trees at Independence Square — refined, melodic, and unhurried.",
    ],
    tiers: [
      { id: "final", name: "Final Phase", price: 48, fee: 4, blurb: "Guaranteed entry.", available: 160, badge: "Popular" },
      { id: "gate", name: "At the Gate", price: 60, fee: 4, blurb: "Pay-on-arrival.", available: 120 },
      { id: "vip", name: "VIP", price: 110, fee: 8, blurb: "Front terrace and welcome drink.", perks: ["Front terrace", "Welcome drink", "Fast-lane entry"], available: 24, badge: "Limited" },
    ],
    image: cover("kamilo-sanclemente"),
    accent: "#eab308",
    attending: 540,
    capacity: 800,
  },
  {
    id: "7",
    slug: "sunset-sessions-ultra-ajay",
    title: "Sunset Sessions: Ultra b2b A-Jay",
    tagline: "A world-exclusive 3-hour sunset back-to-back at the Lotus Tower.",
    category: "Melodic House",
    city: "Colombo",
    area: "Rajagiriya",
    venue: "Lotus Tower Skydeck",
    date: "2026-09-19T16:00:00",
    startTime: "16:00",
    endTime: "22:00",
    ageLimit: 18,
    organizer: { name: "Tickets Ministry" },
    lineupLabel: "Lineup",
    lineup: [
      { name: "Ultra", role: "Headliner · b2b" },
      { name: "A-Jay", role: "Headliner · b2b" },
    ],
    description: [
      "A world-exclusive Sunset Sessions: Ultra and A-Jay go back-to-back for three uninterrupted hours as the sun drops behind the Lotus Tower.",
      "Free entry for holders of a Rebirth of Dusty World ticket. Limited pre-sale for everyone else.",
    ],
    tiers: [
      { id: "presale", name: "Pre-Sale", price: 38, fee: 4, blurb: "Limited early allocation.", available: 140, badge: "Best Value" },
      { id: "gate", name: "At the Gate", price: 50, fee: 4, blurb: "Pay-on-arrival.", available: 160 },
    ],
    image: cover("sunset-sessions"),
    accent: "#d4a017",
    attending: 380,
    capacity: 520,
  },
  {
    id: "8",
    slug: "flying-dust-all-night-long",
    title: "Flying Dust: All Night Long",
    tagline: "One headliner, every hour till sunrise — no support, no breaks.",
    category: "Trance",
    city: "Colombo",
    area: "Port City",
    venue: "Port City Open Grounds",
    date: "2026-11-08T21:00:00",
    startTime: "21:00",
    endTime: "06:00",
    ageLimit: 18,
    organizer: { name: "Tickets Ministry", verified: true },
    lineupLabel: "Lineup",
    lineup: [
      { name: "Enzo Vood", role: "All night long" },
      { name: "Kryptone", role: "Warm-up" },
    ],
    description: [
      "No support, no breaks — just one artist and one long, unbroken night. Enzo Vood takes the Flying Dust floor all night long.",
      "Doors at 9PM. Get in early; this is a journey best taken from the start.",
    ],
    tiers: [
      { id: "final", name: "Final Release", price: 42, fee: 4, blurb: "Guaranteed entry.", available: 260, badge: "Popular" },
      { id: "gate", name: "At the Gate", price: 55, fee: 4, blurb: "Pay-on-arrival.", available: 200 },
      { id: "vip", name: "VIP", price: 110, fee: 8, blurb: "VIP deck, fast lane, cloakroom.", perks: ["Fast-lane entry", "VIP deck", "Free cloakroom"], available: 30, badge: "Limited" },
    ],
    image: cover("flying-dust-all-night-long"),
    accent: "#f2c200",
    attending: 900,
    capacity: 1500,
  },
  {
    id: "9",
    slug: "flying-dust-nye",
    title: "Flying Dust NYE 2026",
    tagline: "Ring in the new year with four headliners and a midnight countdown.",
    category: "Nightlife",
    city: "Colombo",
    area: "Port City",
    venue: "Port City Arena",
    date: "2026-12-31T18:00:00",
    startTime: "18:00",
    endTime: "06:00",
    ageLimit: 18,
    organizer: { name: "Tickets Ministry", verified: true },
    lineupLabel: "Lineup",
    lineup: [
      { name: "Ultra", role: "Headliner" },
      { name: "A-Jay", role: "Headliner" },
      { name: "Vegaz", role: "Headliner" },
      { name: "Noiyse Project", role: "Headliner" },
    ],
    description: [
      "The biggest night of the year. Four headliners, a full production, and a midnight countdown to carry the Dusty World into 2027.",
      "This one goes every year — don't be the one still looking for a ticket on the 31st.",
    ],
    tiers: [
      { id: "presale", name: "Pre-Sale", price: 55, fee: 5, blurb: "Best price before it's dusted.", available: 400, badge: "Best Value" },
      { id: "final", name: "Final Phase", price: 75, fee: 5, blurb: "Guaranteed entry.", available: 520, badge: "Popular" },
      { id: "gate", name: "At the Gate", price: 95, fee: 5, blurb: "Pay-on-arrival.", available: 300 },
      { id: "vip", name: "VIP", price: 180, fee: 12, blurb: "VIP deck, premium bar, midnight champagne.", perks: ["Fast-lane entry", "VIP deck", "Premium bar", "Midnight champagne"], available: 40, badge: "Limited" },
    ],
    image: cover("flying-dust-nye"),
    accent: "#e6b800",
    attending: 2100,
    capacity: 5000,
  },
];

const NOW = "2026-07-15T12:00:00";

export function getEvent(slug: string): EventItem | undefined {
  return EVENTS.find((e) => e.slug === slug || e.id === slug);
}

export function upcomingEvents(): EventItem[] {
  return [...EVENTS]
    .filter((e) => e.date >= NOW)
    .sort((a, b) => a.date.localeCompare(b.date));
}

export function featuredEvents(): EventItem[] {
  return EVENTS.filter((e) => e.featured);
}

/** Most in-demand upcoming events, by crowd size. */
export function trendingEvents(limit = 6): EventItem[] {
  return [...upcomingEvents()]
    .sort((a, b) => b.attending - a.attending)
    .slice(0, limit);
}
